projekt/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projekt.Models;

namespace projekt
{
    [Authorize(Roles = "admin")]
    public class BookController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Book/
        public ActionResult Index()
        {
            return View(db.BookModels.ToList());
        }

        [AllowAnonymous]
        // GET: /Book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookModel bookmodel = db.BookModels.Find(id);
            if (bookmodel == null)
            {
                return HttpNotFound();
            }
            return View(bookmodel);
        }

       

        // GET: /Book/Create
        public ActionResult Create()
        {
            return View(new BookViewModel());
        }

        // POST: /Book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Title,Description,AuthorId,CategoryId,ImageUrl,Isbn,Price, CopiesCount")] BookViewModel bookmodel)
        {
            if (ModelState.IsValid)
            {
                BookModel book = new BookModel(bookmodel);
                db.BookModels.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bookmodel);
        }

        // GET: /Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookModel bookmodel = db.BookModels.Find(id);
            if (bookmodel == null)
            {
                return HttpNotFound();
            }
            return View(new BookViewModel(bookmodel));
        }

        // POST: /Book/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Title,Description,AuthorId,CategoryId,ImageUrl,Isbn,Price")] BookViewModel bookviewmodel)
        {
            if (ModelState.IsValid)
            {
                BookModel bookmodel = new BookModel(bookviewmodel);
                db.Entry(bookmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookviewmodel);
        }

        // GET: /Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookModel bookmodel = db.BookModels.Find(id);
            if (bookmodel == null)
            {
                return HttpNotFound();
            }
            return View(bookmodel);
        }

        // POST: /Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookModel bookmodel = db.BookModels.Find(id);
            db.BookModels.Remove(bookmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projekt/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using projekt.Models;

namespace projekt.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> um =
            new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        public ActionResult Index()
        {
            if (Session["cart"] == null)
            {
                Session["cart"] = new List<BookCartHelper>();
            }
            return View(Session["cart"] as List<BookCartHelper>);
        }

        [HttpPost]
        public ActionResult AddToCart(int bookId)
        {
            if (Session["cart"] == null)
            {
                Session["cart"] = new List<BookCartHelper>();
            }
            BookModel bookModel = db.BookModels.Find(bookId);
            List<BookCartHelper> bookList = Session["cart"] as List<BookCartHelper>;
            BookCartHelper book = bookList.Find(x => x.Book.Id == bookId);
            if (book != null)
            {

                book.Count++;
                
            }
            else
            {
                bookList.Add(new BookCartHelper(bookModel));
            }
            return PartialView("_CartPartial", Session["cart"] as List<BookCartHelper>);
        }

        public ActionResult GetCart()
        {
            if (!(Session["cart"] is List<BookCartHelper>))
            {
                return PartialView("_CartPartial", new List<BookCartHelper>());
            }
            return PartialView("_CartPartial", Session["cart"] as List<BookCartHelper>);
        }

        public ActionResult DeleteItem(int id)
        {
            List<BookCartHelper> books = Session["cart"] as List<BookCartHelper>;
            books.RemoveAt(id);
            return View("Index", books);
        }

        public ActionResult ComputePrice()
        {
            List<BookCartHelper> bookList = Session["cart"] as List<BookCartHelper> ?? new List<BookCartHelper>();
            return Json(new Dictionary<String, Decimal>
            {
                {"price", bookList.Sum(x => x.Count * x.Book.Price)}
            });
        }

        public ActionResult Confirm()
        {
            OrderModel orderModel = new OrderModel
            {
                UserId = User.Identity.GetUserId(),
                DateOfOrder = DateTime.Now
            };
            db.OrderModels.Add(orderModel);
            db.SaveChanges();
            List<BookCartHelper> bookList = Session["cart"] as List<BookCartHelper>;
            foreach(var book in bookList)
            {
                CartModel cartModel = new CartModel {OrderId = orderModel.Id, BookId = book.Book.Id, Count = book.Count};
                db.CartModels.Add(cartModel);
            }
            db.SaveChanges();
            Session["cart"] = new List<BookCartHelper>();
            return View(orderModel);
        }
	}
}

projekt/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using projekt.Models;

namespace projekt.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Order/
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var ordermodels = db.OrderModels.Include(o => o.User);
            return View(ordermodels.ToList());
        }

        public ActionResult MyOrders()
        {
            var id = User.Identity.GetUserId();
            var ordermodels = db.OrderModels.Include(o => o.User).Where(o => o.UserId == id);
            return View("Index", ordermodels.ToList());
        }

        // GET: /Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderModel ordermodel = db.OrderModels.Find(id);
            if (ordermodel == null)
            {
                return HttpNotFound();
            }
            return View(ordermodel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projekt/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using projekt.Models;
using WebGrease.Css.Extensions;

namespace projekt.Controllers
{
    public class UserController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private UserManager<ApplicationUser> um =
            new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        private IdentityManager imManager = new IdentityManager();

        // GET: /User/
        public ActionResult Index()
        {
            List<UserViewModel> users = new List<UserViewModel>();
            foreach (var user in db.Users)
            {
                users.Add(new UserViewModel(user));
            }
            return View(users);
        }

        // GET: /User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        // GET: /User/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = um.FindById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            List<SelectListItem> roles = new List<SelectListItem>();
            foreach (IdentityRole role in db.Roles)
            {
                roles.Add(new SelectListItem
                {
                    Text = role.Name,
                    Value = role.Id,
                    Selected = user.Roles.ToList().Find(r => r.Role.Name == role.Name) != null
                });
            }

            ViewBag.Roles = roles;
            return View(new UserViewModel(user));
        }

        // POST: /User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Login,Roles")] UserViewModel userviewmodel)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser au = um.FindById(userviewmodel.Id);
                imManager.ClearUserRoles(userviewmodel.Id);
                userviewmodel.Roles.ForEach(r => imManager.AddUserToRole(userviewmodel.Id, imManager.GetRoleById(r).Name));
                au.UserName = userviewmodel.Login;
                return RedirectToAction("Index");
            }
            return View(userviewmodel);
        }

        // GET: /User/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = um.FindById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(new UserViewModel(user));
        }

        // POST: /User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser au = um.FindById(id);
            var user = db.Users.First(u => u.Id == id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projekt/Views/Shared/_CartPartial.cshtml
@model IEnumerable<projekt.Models.BookCartHelper>
<ul id="cart" class="nav">
    <li class="nav-header">Koszyk</li>

    @{ decimal price = 0; }
    @foreach (var book in Model)
    {
        price += book.Count*book.Book.Price;
        <li>@book.Count x @book.Book.Title</li>
    }


    @if (@Model.LongCount() != 0)
    {
        <li>Cena łączna: @price</li>
        <li>@Html.ActionLink("Potwierdź", "Index", "Cart")</li>

    }
</ul>

projekt/Views/Shared/_CategoryPartial.cshtml
@model IEnumerable<projekt.Models.Category>
@foreach (var category in Model)
{
    <li>@Html.ActionLink((string)category.Name, "BookList", "Home", new { categoryId = category.Id }, null)</li>
}

projekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style type="text/css">
        body {
            padding-bottom: 40px;
            padding-top: 60px;
        }

        .sidebar-nav-fixed {
            width: 15%;
        }
    </style>
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
<div class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Project name</a><a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="glyphicon glyphicon-bar"></span>
                <span class="glyphicon glyphicon-bar"></span>
                <span class="glyphicon glyphicon-bar"></span>
            </a>
        </div>
        <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
            </ul>
            @Html.Partial("_LoginPartial")




        </div>
        <!--/.navbar-collapse -->
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sidebar-nav-fixed affix">
                <div class="well">
                    <ul class="nav ">
                        <li class="nav-header">Kategorie:</li>
                        @Html.Action("GetCategories", "Category")
                    </ul>

                </div>
                @if (Request.IsAuthenticated)
                {
                    <div class="well">
                        <ul class="nav">
                            <li class="nav-header">Panel użytkownika:</li>
                            <li>@Html.ActionLink("Twoje zamówienia", "MyOrders", "Order")

                        </ul>

                    </div>
                }
                
                @if (User.IsInRole("admin"))
                {
                    <div class="well">
                        <ul class="nav">
                            <li class="nav-header">Panel administracyjny:</li>
                            <li>@Html.ActionLink("Kategoria", "Index", "Category")</li>
                            <li>@Html.ActionLink("Użytkownicy", "Index", "User")</li>
                            <li>@Html.ActionLink("Role", "Index", "Role")</li>
                            <li>@Html.ActionLink("Autorzy", "Index", "Author")</li>
                            <li>@Html.ActionLink("Książka", "Index", "Book")</li>
                            <li>@Html.ActionLink("Zamówienia", "Index", "Order")</li>

                        </ul>

                    </div>
                }
                <!--/.well -->
            </div>
            <!--/sidebar-nav-fixed -->
        </div>
        <!--/span-->
        <div class="col-md-6">
            <div class="">
                @RenderBody()
            </div>

        </div>
        <!--/span-->
        <div class="col-md-3">
            <div class="sidebar-nav-fixed pull-right affix">
                <div id="cart-box" class="well">
                   @Html.Action("GetCart", "Cart")
                </div>
                <!--/.well -->
            </div>
            <!--/sidebar-nav-fixed -->
        </div>
        <!--/span-->
    </div>
    <!--/row-->

    <footer>
        <p>© Footer</p>
    </footer>
</div>
<!--/.fluid-container-->
<!-- /#wrapper -->
    <script>

        $('.addToCart').click(function() {
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddToCart", "Cart")',
                contenttype: "application/html; charset=utf-8",
                data: { bookId: $(this).attr("data-book-id") },
                success: function(result) {
                    var $cart = $('#cart');
                    $cart.replaceWith(result);
                },
                error: function(error) {
                    console.log("error");
                    console.log(error);
                }
            });
        });

    </script>

</body>
</html>